name: Test action

on:
  push:
    branches: [ master ]
jobs:
    test-action:
        name: 'Test actions'
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkouts'
              uses: actions/checkout@master
            - name: 'Test curl actiosn'
              uses: beetlikeyg087/curl@master
              with:
                url: 'https://reqres.in/api/users'
                method: 'POST'
                accept: 201
                body: '{ "name": "breeze",  "job": "devops" }'
                is_debug: true,
                custom-config: .github/workflows/curl-config.json
                
                
                
  
